export const HIDE_BANNER = 'HIDE_BANNER';
export const NETWORK = 'NETWORK';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SKIP_AUTH = 'SKIP_AUTH';
export const ERRORS = {
  ERROR_FIREBASE_LOGIN: 'ERROR_FIREBASE_LOGIN',
  ERROR_FIREBASE_LOGOUT: 'ERROR_FIREBASE_LOGOUT',
  ERROR_GOOGLE_AUTH: 'ERROR_GOOGLE_AUTH',
};
